spring:
  datasource:
    url: jdbc:h2:mem:userdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS journal_database\;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update       # or "create-drop" if you want a clean DB each run
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: journal_database
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8086
  error:
    include-message: always

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351